version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine # The 'alpine' version is much smaller, saving even more space!
    container_name: mibiatchicar_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: